### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by dailyforest**
add Token CATID

### CODE REVIEW

**Comment by dailyforest** [comment]
some thing wrong ?

**Comment by dailyforest** [comment]
Change vendor 
add NFT Collection

**Comment by rualekseev** [comment]
TIP 3:

[done] Create your token
[done] Mint tokens
[done] Transfer ownership for root contract

[not done] Create DEX pair with wvenom or usdt token 
[not done] burn or lock LP tokens

recommended
- setup vesting for free tokens

**Comment by dailyforest** [comment]
> TIP 3:
> 
> [done] Create your token [done] Mint tokens [done] Transfer ownership for root contract
> 
> [not done] Create DEX pair with wvenom or usdt token [not done] burn or lock LP tokens
> 
> recommended
> 
> * setup vesting for free tokens

done all Create LP 
and locked

**Comment by rualekseev** [comment]
@dailyforest Sorry, My bad.

[done] Create your token
[done] Mint tokens
[done] Transfer ownership for root contract
[done] Create DEX pair with wvenom or usdt token
[done] burn or lock LP tokens

**Pull request merged**
