### PR TITLE
feat: add mau coin

### PR DESCRIPTION
**Pull request by haha-mike**

### CODE REVIEW

**Comment by rualekseev** [comment]
TIP 3:

[done] Create your token
[done] Mint tokens
[done] Create DEX pair with wvenom or usdt token

- Transfer ownership for root contract
- burn or lock LP tokens

**Comment by rualekseev** [comment]
@haha-mike Can you fix it?

**Comment by haha-mike** [comment]
@rualekseev sure

**Comment by haha-mike** [comment]
Fixed.

**Comment by rualekseev** [comment]
TIP 3:

[done] Create your token
[done] Mint tokens
[done] Create DEX pair with wvenom or usdt token

[done] Transfer ownership for root contract
[done] burn or lock LP tokens

**Pull request merged**
