### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by Valetosnamibe**
VenYacht $YACHT 
Venom Yacht Club

    {
      "name": "VenYacht",
      "chainId": 1,
      "symbol": "YACHT",
      "decimals": 9,
      "address": "0:8c6667843ed6f8264ca9cf58c978debf7cc08c343c1a9f74f9bcca03d68430ae",
      "logoURI": "https://impulsefinance.s3.us-east-1.amazonaws.com/images/1711562908128venyacht.PNG",
      "version": 5,
      "verified": false,
      "vendor": "Venom Yacht Club"
    },

### CODE REVIEW

**Comment by rualekseev** [comment]
[done] Create your token
[done] Mint tokens
[done] Create DEX pair with wvenom or usdt token


- Transfer ownership for root contract
- burn or lock LP tokens

**Comment by AlphVE** [comment]
done
Hash new owner 0:Dead https://venomscan.com/messages/4068331dbcb39bebdf93f760ff452a5b62a2e664d2fced882be52f81c4a0dbb1

Burn or lock LP tokens ✅

**Comment by Valetosnamibe** [comment]
Ready,Done

**Comment by Valetosnamibe** [comment]
burn or lock LP tokens https://web3.world/pools/0:c19ea14f93b453b0906faed5c8b40133c6761dcd7f7ca50ce685773d3fca8534
Transfer ownership for root contract https://venomscan.com/accounts/0:8c6667843ed6f8264ca9cf58c978debf7cc08c343c1a9f74f9bcca03d68430ae

**Comment by rualekseev** [comment]
[done] Create your token
[done] Mint tokens
[done] Create DEX pair with wvenom or usdt token
 [done] Transfer ownership for root contract
 [done] 98% burn or lock LP tokens
 ~74% free float

**Pull request merged**
